ntucker/anansi

examples/found/package.json, examples/typescript/package.json, packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/src/prod.js
Adds profile mode to enable React profiler in production. Tested by running `yarn link` and using production build of another project.
=> [Feature] Add profile mode

packages/webpack-config-anansi/src/index.js
`--mode=production` should override NODE_ENV=test for instance.
This is logical because running a command in CLI is more specific as it is a case-by-case basis; whereas env persists between commands. More specific should always override less specific.
=> [webpack][breaking] CLI mode should override ENV variables set

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, yarn.lock
https://github.com/babel/preset-modules was released today and announced at google dev summit. It produces more streamlined output by attempting to target es6 rather than es5 in it's transforms.
This currently only uses `preset-modules` instead of `preset-env` if target is set to `{ esmodules: true }` as this is only intended for that specific set of browsers.
=> feat: Use preset-modules when target is set to esmodules: true

packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/src/base/index.js
For prod builds, setting publicPath is important - even in local mode.
=> enhance: ENV configurable publicPath

packages/webpack-config-anansi/src/prod.js, yarn.lock
Development having a fallback title can be useful to more obviously catch but in production it's best to have something safe like empty string.
=> enhance: Change default production htmlOptions to have empty title

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js
https://www.npmjs.com/package/babel-plugin-root-import#custom-root
This is especially useful for monorepos
=> feat: Add rootPathRoot option

examples/typescript/package.json, examples/typescript/src/App.tsx, examples/typescript/src/index.tsx, examples/typescript/src/pages/Home/index.tsx, packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/dev.js, yarn.lock
BREAKING: Add react-refresh to dev deps instead of hot-reloader
Also remove any hot-reloader setup code
react-refresh is the new hot-reloading mechanism that is faster, more reliable and works with hooks!
=> feat: Use react fast-refresh instead of hot-reloader

packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js
This is the directory that babel takes as the root directory when deciding which configuration file to use.
=> [TASK] Add babelRoot to webpack config generator

packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json
https://babeljs.io/blog/2019/07/03/7.5.0#dynamic-import-9552-https-githubcom-babel-babel-pull-9552-and-10109-https-githubcom-babel-babel-pull-10109
Since 7.5, preset-env now does similar detection for dynamic imports. However, it supports more module targets than just commonjs so this is more powerful.
It does the same detection algorithm to understand when things like webpack and parcel and using it so as to let them perform the transform.
=> enhance: Let preset-env handle dynamic imports

packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/prod.js, yarn.lock
This will generally help with waterfalls as this is a tiny chunk that is required to start downloading all other assets. Removing this from the latency waterfall by default should be a good performance benefit.
=> enhance: Inline webpack runtime chunk in prod

packages/generator-js/package.json
Fixes #25 
installPeers() requires the package to be installed to inspect the package.json
=> fix: Include needed peerdeps from eslint-plugin

salus.yaml, yarn.lock
New vuln: https://www.npmjs.com/advisories/1523 which affects zipObjectDeep. This is not used in anansi so we ignore since there is not mitigation for now.
=> internal: Yarn.lock security

examples/linaria/.babelrc.js, examples/linaria/.eslintrc.js, examples/linaria/.gitignore, examples/linaria/README.md, examples/linaria/package.json, examples/linaria/src/App.tsx, examples/linaria/src/index.tsx, examples/linaria/tsconfig.json, examples/linaria/webpack.config.js, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/base/scss.js, packages/webpack-config-anansi/src/prod.js, yarn.lock
- Added linaria example for testing - this integrates simply by adding the loader to the js file processing list
```js
config.module.rules[1].use.push({
loader: 'linaria/loader',
options: {
sourceMap: argv?.mode !== 'production',
},
});
```
- Fixed longstanding hotreloading bug with css changes
- Always use extracss instead of style-loader
=> feat: Support linaria and other css flexibility

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, packages/generator-js/package.json, packages/webpack-config-anansi/package.json, yarn.lock
Tested using
```typescript
export class PostResource extends Resource {
readonly id: number | undefined = undefined;
readonly userId: number | undefined = undefined;
readonly title: string = '';
readonly body: string = '';
pk() {
return this.id?.toString();
}
static urlRoot = '';
static {
this.urlRoot = 'https://jsonplaceholder.typicode.com/posts/';
}
}
```
However, not adding this permanently as this feature is not currently supported by eslint and typescript parsers. Usage should only be in plain js for the time being because of this.
=> feat: Support class static initialization blocks

package.json, packages/webpack-config-anansi/src/base/index.js, yarn.lock
BREAKING CHANGE: module resolution now looks in package's node_modules
before hoisted
- Adding: a particular package's node_modules based on absolute path to check before general node_modules. This should only make a major difference in monorepos
- Also avoided hoisting some webpack plugins that storybook also uses to ensure our webpack config resolves our version
More info: https://medium.com/rewire-to/webpack-module-resolution-within-a-monorepo-or-how-i-stopped-bundling-two-versions-of-react-7c1d8c31d5a0
=> fix: Improve monorepo package resolution

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js, yarn.lock
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
Upgrading to the new transform is completely optional, but it has a few benefits:
- With the new transform, you can use JSX without importing React.
- Depending on your setup, its compiled output may slightly improve the bundle size.
- It will enable future improvements that reduce the number of concepts you need to learn React.
- Babel plugin checks caller for hasJsxRuntime. This is also used by next.js webpack
- webpack sets caller if semver of 16.14 or above of react is found from project directory
- Obsoletes [plugin-transform-react-inline-elements](https://babeljs.io/docs/en/babel-plugin-transform-react-inline-elements)
- Fixed: reactConstantElementsOptions and hotreloader options are now correctly read
=> feat: Support new jsx transform for react 17

packages/generator-js/src/base/index.ts, packages/generator-js/src/base/templates/tsconfig.json, packages/generator-js/src/spa/templates/src/index.tsx
Land this when 4.1 is out: https://github.com/microsoft/TypeScript/issues/40124 Nov 17
This eliminates the error when React import is missing in tsx files
=> enhance: Use TypeScript 4.1 jsx transform support

package.json, packages/webpack-config-anansi/src/base/index.js
After further testing https://github.com/ntucker/anansi/pull/49 sometimes results in packages being unable to resolve their dependencies in cases where their dependencies get hoisted.
My conclusion is it's best not to mess with module resolution behavior, but rather focus on the really problem - hoisting. As far as I can tell peerDeps will still work correctly, so by eliminating hoisting where:
- packages might have multiple versions in the monorepo
- yet only one version should be loaded for a given application
If we ensure those packages never get hoisted, then it will always resolve to the local application one. It is important to use peerdeps in these cases, or other packages might end up pointing to a different version. However, this is already required when using packages externally …
=> fix: Use normal node resolution

packages/generator-js/src/base/index.ts, packages/generator-js/src/spa/index.ts, packages/generator-js/src/storybook/templates/.storybook/main.js, packages/generator-js/src/webpack/index.ts
Storybook currently does not support webpack 5, so if this feature is used we should ensure v4 is installed instead.
- Built new project using storybook feature only.
=> fix: Use webpack 4 if storybook is used

.github/workflows/commitlint.yml
Hopefully this blocks merge completing.
Based on: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/4
=> run commitlint on merge

packages/webpack-config-anansi/src/base/constants.js, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/base/scss.js, packages/webpack-config-anansi/src/prod.js, packages/webpack-config-anansi/src/storybook.js, packages/webpack-config-anansi/src/utils.js
To ensure the loaders from this package are used, a special `resolveLoader` config is set.
This is not ideal for two reasons:
- makes that option fragile against user change
- the option itself could potentially break apart.
Here we use require.resolve() to ensure absolute paths for all loaders we specify. This should be strong against any other configs - so long as these are not modified.
This means we need to be a bit more fancy with our loader matching algo - so we use a regex.
Bonus: this also makes this compatible with `PnpWebpackPlugin`
Verified this would resolve correctly still in an independent project by modifying its lib source directly.
=> enhance: Remove need for fancy loader resolution

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, yarn.lock
Aliasing is useful for the new package.json exports:
```bash
RESOLVER_ALIAS='{"@rest-hooks/test":"#internal"}' yarn build:lib
```
- Manually pasted the code into node_modules in rest-hooks, tried env variables
- Test existing features via anansi example builds
=> feat: Add import aliasing options

.github/workflows/bundle_size.yml, .github/workflows/lighthouse.yml, package.json, packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/src/base/index.js
- Build relevant packages in prepare script, so getting started works
- Webpack: add --env nohash that outputs consistent filenames
- build:sizecompare to exploit this for bundlesize checker
=> feat: Add --env nohash option

package.json, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/plugins/InlineChunkHtmlPlugin.js, packages/webpack-config-anansi/src/prod.js, yarn.lock
CRA is a bad project to depend on as it is horribly out of date and doesn't update security vulns, including setting exact package deps.
Here we resolve the browserslist security vuln by:
- react-dev-utils (CRA) is still needed by storybook, which is for dev only, so we add resolutions
- inline the simple webpack plugin InlineChunkHtmlPlugin to remove dependency from our packages
=> pkg: Remove react-dev-utils

.github/workflows/combine-prs.yml
I'm the maintainer of https://github.com/hrvey/combine-prs-workflow and we just made a new release - https://github.com/hrvey/combine-prs-workflow/releases/tag/1.2.0 - to fix a potential injection attack based on a PR with a malicious branch name. I've included the fix for this here, to make sure you noticed and make it as easy as possible for you to patch :)
=> internal: Fix potential injection vulnerability

packages/webpack-config-anansi/src/plugins/ErrorOverlayEntry.js
See https://github.com/facebook/create-react-app/pull/11105
=> fix: fast refresh stops on needed bail outs

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js
Make 'modules' option more clear.
Ensure `useESModules` defaults to false if transforms to commonjs are used.
=> fix: If modules is forced off - don't default runtime to esm version

packages/webpack-config-anansi/src/base/index.js
BREAKING CHANGE: Importing scss file requires including the file
extension
=> enhance: Only support TypeScript and default webpack extensions

examples/linaria/src/App.tsx, examples/linaria/src/Media.tsx, examples/linaria/src/angle-down-solid.svg, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js, yarn.lock
https://github.com/callstack/linaria/pull/879 breaks a lot of things:
- urls cannot be resolved using webpack resolution rules
- svgr cannot work because issuer queries break and we don't know we should be considering the url from a css source
- react-refresh breaks due to detecting it is in a js file when in fact it's processing css
So we publish a loader where this is reverted.
We also introduce the url-inside linaria use case for an svg with absolute resolution to ensure this is accounted for.
=> fix: Linaria works with svg urls

.github/workflows/bundle_size.yml, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/storybook.js, yarn.lock
Performance analysis in a very large project for both prod builds and initial dev build with no cache shows thread loader with similar performance without. This is best case scenario for thread-loader actually helping.
Thread-loader comes with [problematic limitations](https://webpack.js.org/loaders/thread-loader/#root):
-  Loaders cannot emit files.
-  Loaders cannot use custom loader API (i. e. by plugins).
-  Loaders cannot access the webpack options.
These limitations have caused problems in linaria as well as resolve plugins.
Due to this, we're removing thread loader altogether.
=> enhance: Remove thread-loader

packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/base/linariaFileCache.js, yarn.lock
https://github.com/callstack/linaria/issues/897 appears to be resolved by matching the file cache extension in our custom cache with the loader special case detection.
Not sure if this is due to other ecosystem fixes; but this has been validated with react-refresh in both the example/linaria and example/concurrent project.
=> enhance: Switch back to mainstream linaria loader

examples/concurrent/src/app/index.tsx, examples/concurrent/src/index.tsx, examples/concurrent/src/pages/Home/index.tsx, packages/core/package.json, packages/core/src/laySpouts.tsx, packages/core/src/scripts/startDevserver.ts, packages/webpack-config-anansi/src/dev.js, packages/webpack-config-anansi/src/plugins/ErrorOverlayEntry.js, yarn.lock
By forcing one file output bundle for server when using startDevserver; and using `import-fresh` we are able to re-import all output modules on every build change to allow the SSR to get the latest changes. This avoids hydration mismatches as developers edit their code.
Suppress `The server could not finish this Suspense boundary` error from opening overlay as this is expected sometimes depending on desired behavior.
=> feat: SSR uses webpack devserver and responds to code changes

packages/webpack-config-anansi/src/dev.js
Compile entrypoints and dynamic imports only when they are in use. 
https://webpack.js.org/configuration/experiments/#experimentslazycompilation
=> enhance: Use lazy-compilation in dev mode for faster build times

examples/concurrent/package.json, packages/cli/README.md, packages/cli/package.json, packages/cli/run.js, packages/core/package.json, packages/core/src/scripts/index.ts, packages/core/src/scripts/serve.ts, packages/core/src/scripts/startDevserver.ts, yarn.lock
```bash
Usage: anansi serve [options] <entrypath>
runs server for SSR projects
Arguments:
entrypath             Path to entrypoint
Options:
-p, --pubPath <path>  Where to serve assets from
-d, --dev             Run devserver rather than using previously compiled output
-h, --help            display help for command
```
```json
{
"start": "anansi serve --dev ./src/index.tsx",
"start:prod": "anansi serve --pubPath=/assets/ ./dist-server/App.js",
}
```
=> feat: Add anansi serve command

packages/core/package.json, packages/core/src/scripts/startDevserver.ts, yarn.lock
fs-monkey breaks modern require specifications like using 'exports' fields. fs-require maintains better compatibility by not monkey patching.
=> enhance: Improve devserver node 'require' reliability

examples/concurrent/src/index.server.tsx, examples/concurrent/src/index.tsx, packages/core/src/index.server.ts, packages/core/src/index.ts, packages/core/src/laySpouts.tsx, packages/core/src/spouts/DocumentComponent.tsx, packages/core/src/spouts/csp.ts, packages/core/src/spouts/document.server.tsx, packages/core/src/spouts/document.tsx, packages/core/src/spouts/json.server.tsx, packages/core/src/spouts/json.tsx, packages/core/src/spouts/restHooks.server.tsx, packages/core/src/spouts/restHooks.tsx, packages/core/src/spouts/rhHelp.tsx, packages/core/src/spouts/router.tsx, packages/core/src/spouts/types.ts, packages/generator-js/src/ssr/templates/src/index.server.tsx
- JSON spout adds initData to each
```ts
const spouts = JSONSpout()(
documentSpout({ title: 'anansi' })(
restHooksSpout()(
routerSpout({
useResolveWith: useController,
createRouter,
})(appSpout),
),
),
);
export default floodSpouts(spouts);
```
- nonce is added to init props (with manifest req,res, etc)
- initData return value is used by JSON spout to embed to be loaded. takes functions to run at final stage
```ts
{
initData: {
...nextProps.initData,
resthooks: () => store.getState(),
},
}
```
```ts
const spouts = prefetchSpout('controller')(
documentSpout({
title: 'anansi',
})(
JSONSpout()(
restHooksSpout()(
routerSpout({ useResolveWith: useController, createRouter })(appSpout),
),
),
),
);
export default laySpouts(spouts);
```
=> feat: Add CSP support

packages/core/package.json, yarn.lock
`@anansi/core@npm:0.14.0 [a8f24] doesn't provide rest-hooks (p7e75d), requested by @rest-hooks/ssr`
=> fix: Provide rest-hooks package for rest-hooks/ssr

examples/concurrent/.eslintrc.js, examples/concurrent/src/index.server.tsx, examples/typescript/.eslintrc.js, packages/core/src/spouts/restHooks.server.tsx, packages/core/src/spouts/router.server.tsx, packages/core/src/spouts/router.tsx, packages/core/src/spouts/types.ts
When a Spout provides a prop it should no longer need that prop. We must separate each provided prop into its own intersection for TypeScript to correctly infer this. Unfortunately this does require a somewhat non intuitive crafting for Spout authors but it's the best we can do for now.
=> fix: Spout type removes provided props from needed props

.circleci/config.yml, examples/concurrent/package.json
If there is only one workspace with a script, it will be run from any location - thus foreach runs that same script X times where X is the number of workspaces.
For test - just add another one as we anticipate having more test suites. For storybook we will call the specific workspace directly as we don't expect to add storybook to any other workspace.
=> internal: Don't repeat work in CI

packages/webpack-config-anansi/src/prod.js
https://github.com/webpack-contrib/terser-webpack-plugin/issues/21 has long been fixed so disabling is not necessary.
Now 6s full production build:
```bash
assets by path *.js 704 KiB
assets by chunk 264 KiB (id hint: vendors)
asset 690-0d86d44ea3431adc.chunk.js 90 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
asset 224-978f26359dba3628.chunk.js 55.3 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
asset 126-13d3e8ed527e1961.chunk.js 39.9 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
asset 163-3d0dd12cf508907f.chunk.js 33.7 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
asset 65-951551524311aa7d.chunk.js 19.6 KiB [emitted] [immutable] [minimized] (id hint: vendors) 1 related asset
asset …
```
=> enhance: Enable terser parallelism in WSL

packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/base/linariaFileCache.js, packages/webpack-config-anansi/src/dev.js, yarn.lock
We're forced to use loaders to have dual imports (https://react-svgr.com/docs/webpack/#use-with-url-loader-or-file-loader). However, the last file-loader uses outdated loader-utils so it does not support the new hashing method.
Use md5 instead of md4 (when xxhash64 is not supported) as that is still supported in node 18.
=> fix: Production builds work in node 18

examples/concurrent/package.json, examples/concurrent/src/index.tsx, examples/linaria/package.json, examples/typescript/package.json, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, packages/core/package.json, packages/generator-js/package.json, packages/pojo-router/package.json, packages/router/package.json, packages/webpack-config-anansi/package.json, renovate.json, yarn.lock
core-js is becoming the canonical location for all polyfills. Thusly, by using it as much as possible, we can ensure minimal extraneous code.
This means we prefer to use @babel/runtime-corejs3 over @babel/runtime if it is available, as it defers to core-js when available.
`useBuiltIns` should be set to 'usage' for libraries, and for applications either 'entry' or 'usage' depending on whether polyfills are handled specially. Which polyfills are loaded *are* based on the target; which means without doing anything extra 'usage' is the most efficient method.
`useBuiltIns` should default to 'entry' in the future, as this will ensure the minimum amount of code. However, this would be a breaking change so we are holding off for this release.
=> feat: Use @babel/runtime-corejs3 if available

packages/webpack-config-anansi/README.md, packages/webpack-config-anansi/index.d.ts, packages/webpack-config-anansi/src/base/css.js, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/dev.js, packages/webpack-config-anansi/src/index.js, packages/webpack-config-anansi/src/nobuild.js, packages/webpack-config-anansi/src/prod.js
For JS extensions, CSS can be difficult, so this adds an option to disable or control CSS extraction from the webpack config.  By default, no changes are made to the output, but this allows the ability to disable the extraction plugin or set any of its options.
=> feat: Add option to disable CSS extraction

packages/webpack-config-anansi/src/base/index.js
https://github.com/ntucker/anansi/commit/32bd97b7d3b2f9ff0697602a9747927a4fbf7ffc introduced [extensionAlias](https://webpack.js.org/configuration/resolve/#resolveextensionalias) usage to make importing a local .js file resolve .tsx. However, this also made it not work for ESM packages with exports members.
This is likely a bug as it should fallback. However, by making it look for .js first it seems to work for both cases.
References:
- https://github.com/vercel/next.js/pull/45423
- https://github.com/webpack/webpack/issues/13252
=> fix: Compatibility with ESM exports packages

packages/core/package.json, packages/core/src/scripts/getWebpackConfig.ts, packages/core/src/scripts/package.json, packages/core/src/scripts/serve.ts, packages/core/src/scripts/startDevserver.ts, packages/core/src/scripts/webpack-logging.d.ts
ESM can do anything.
We still compile the server file to commonjs though so that we can use memfs 'require'
=> enhance: Scripts are now ESM

packages/core/src/spouts/DocumentComponent.tsx, packages/core/src/spouts/csp.ts, packages/core/src/spouts/document.server.tsx
HTTP Headers for CSP are more powerful; for instance, allowing Content-Security-Policy-Report-Only.
In dev-mode we report only - which allows us to keep the policy exactly the same so developers can become aware of any issues with console error reports when something fails CSP.
=> enhance: Move CSP to header; report-only in dev-mode

.yarnrc.yml, examples/typescript/package.json, package.json, packages/cli/package.json, packages/core/package.json, packages/generator-js/package.json, packages/jest-preset-anansi/package.json, packages/jest-preset-anansi/src/jest-preset.ts, packages/pojo-router/package.json, packages/router/package.json, packages/storybook/package.json, packages/ts-utils/package.json, packages/webpack-config-anansi/package.json, yarn.lock
Found out about https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
This allows us to centralize all dev deps used in scripts to the root, as well as shared options.
```json
{
"dependencies": {
"typescript": "^3.8.0"
},
"scripts": {
"g:tsc": "cd $INIT_CWD && tsc"
}
}
```
```json
{
"scripts": {
"build": "yarn g:tsc"
}
}
```
=> internal: Hoist scripts to root

.circleci/config.yml, examples/concurrent/package.json, examples/linaria/package.json, package.json, packages/generator-js/src/webpack/index.ts, packages/webpack-config-anansi/package.json, yarn.lock
Linaria 4.5 is broken; let's revert to last working version
In meantime we'll add a devserver test to our CI to make sure dev build breaking doesn't get merged. This will prevent future releases having this problem. This currently only tests that the dev build starts and not what the results are. To check results I would need to setup a proper browser test suite like playwright
=> fix: Revert linaria to working version

examples/concurrent/package.json, examples/linaria/package.json, package.json, packages/babel-preset-anansi/index.js, packages/generator-js/src/webpack/index.ts, packages/webpack-config-anansi/package.json, renovate.json, yarn.lock
Linaria 5 introduced caller.name to determine when it is the caller. This allows us to disable react refresh in this case.
=> pkg: Upgrade linaria to 5

examples/concurrent/webpack.config.cjs, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/storybook.js
This is a workaround for https://github.com/Anber/wyw-in-js/issues/30 wyw-in-js not being able to process some of the info.
https://github.com/storybookjs/storybook/blob/f013ffeb03377c6e1b76a9aabd94c180e3e3ef38/code/builders/builder-webpack5/src/preview/virtual-module-mapping.ts#L52 includes some storybook specific virtual files that are not compatible. However, these are not user files so there is no reason to run our loader processing on them - we can simply exclude those and let them fallback to how storybook rules work.
- Explicitly exclude known problematic https://github.com/storybookjs/storybook/blob/f013ffeb03377c6e1b76a9aabd94c180e3e3ef38/code/builders/builder-webpack5/src/preview/virtual-module-mapping.ts#L52 in storybook rule
- Update ts/js rule to more correctly match only …
=> fix: Storybook builds by not running full loader on storybook virtua files

packages/babel-preset-anansi/CHANGELOG.md, packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js
"Class fields are not enabled. Please add `@babel/plugin-transform-class-properties` to your configuration."
appears when not transforming, due to the default decorators targeting a version that always expects them to exist.
Simply targeting the latest fixes this. This should be considered a breaking change in v5
Breaking:
* Decorators targets '2023-05' of the spec by default (from '2018-09' previously)
* See more https://babeljs.io/docs/babel-plugin-proposal-decorators#version
* If you want to continue targeting an older version, you will need to manually add `@babel/plugin-transform-class-properties`
* `loose` no longer changes the default spec target (used to be 'legacy')
Other changes:
- Setting decoratorsOptions to target legacy, will force class transforms to be enabled, as [this is …
=> enhance: Fix 'Class fields are not enabled.' by using latest decorators standard

.circleci/config.yml, examples/typescript/package.json
Other than testing recent targets, we want to ensure targetting various legacy configs works.
"2018", "2020", "2022"
=> internal: Test builds targetting different browsers

packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/index.js
BREAKING CHANGE: hasJsxRuntime defaults to true
=> Use react's jsx-runtime directly by default

examples/concurrent/src/app/App.tsx, examples/concurrent/src/app/demo.tsx, examples/concurrent/src/index.tsx, packages/pojo-router/README.md, packages/pojo-router/src/Link.tsx, packages/pojo-router/src/hooks.tsx
BREAKING CHANGE: useController renamed to useRouter
Controller naming is too generic. This makes it easier to work with other packages like data-client.
=> feat: useController -> useRouter

babel.config.js, examples/concurrent/package.json, examples/linaria/package.json, examples/typescript/package.json, package.json, packages/babel-preset-anansi/README.md, packages/babel-preset-anansi/__snapshots__/transform2018.test.js.snap, packages/babel-preset-anansi/index.js, packages/babel-preset-anansi/package.json, packages/babel-preset-anansi/presetOutput.test.js, packages/babel-preset-anansi/transform2018.test.js, packages/core/package.json, packages/generator-js/package.json, packages/jest-preset-anansi/package.json, packages/pojo-router/package.json, packages/router/package.json, packages/storybook/package.json, packages/webpack-config-anansi/package.json, packages/webpack-config-anansi/src/base/generateBabelLoader.js, packages/webpack-config-anansi/src/base/index.js, packages/webpack-config-anansi/src/prod.js, renovate.json, yarn.lock
‘usage-global’ | ‘entry-global’ | ‘usage-pure’ | false | undefined
This determines how to handle polyfills.
[plugin reference](https://github.com/babel/babel-polyfills/blob/main/docs/migration.md)
This is the default - it will automatically determine a reasonable default based on other factors.
'usage-pure' when detecting 'library build' (@babel/cli or caller.library is true)
Otherwise, if 'core-js' and '@babel/runtime' package are found, 'usage-global'.
If just 'core-js' is found, 'usage-entry'
Otherwise `false`.
Transforms core-js import into only the polyfills needed for the target environment. This can be best when
a good code-splitting strategy for polyfills is in the place.
Turns
```js
import 'core-js'
```
into
```js
import 'core-js/es/object/has-own'
// whatever else is needed for …
```
=> feat: Improve polyfill packaging
