ntucker/anansi

salus.yaml
yarn.lock

[internal] Re-enable yarn audit in salus

---

packages/webpack-config-anansi/src/index.js
yarn.lock

This causes unexpected behavior as setting it to 'undefined' is the same as not setting it at all as far as defaults are concerned.

enhance: Error on htmlOptions set to 'undefined'

---

packages/babel-preset-anansi/index.js

Messed up order in https://github.com/ntucker/anansi/commit/82592946f5304a2fd972649920e59ccc1dbc6fdf#diff-43bf45077baa51046ffadfa74dac82cf

fix: Fix order of class transforms and flow

---

packages/eslint-plugin/base.js
packages/eslint-plugin/typescript.js

https://github.com/typescript-eslint/typescript-eslint/issues/243

enhance: Drop type-aware rules for performance reasons

---

packages/generator-js/package.json
packages/generator-js/src/app/index.ts
packages/generator-js/src/gulp-prettier.ts
yarn.lock

Template files can leaves some garbage - mostly whitespace. This ensures clean formatted files for new projects.
Note: registerTransformStream only works on entrypoint, not on composed generators - therefore anyone using this generator will need to also registerTransformStream

enhance: Prettier template files on write

---

examples/typescript/package.json
examples/typescript/src/components/ErrorBoundary/index.tsx
examples/typescript/src/data/resources.ts
examples/typescript/src/pages/PostDetail/index.tsx
examples/typescript/src/pages/Posts/PostForm.tsx
examples/typescript/src/pages/Posts/PostListItem.tsx
examples/typescript/src/pages/Posts/index.tsx
examples/typescript/src/pages/Posts/useForm.tsx
package.json
packages/generator-js/package.json
yarn.lock

Antd 4 includes substantial bundlesize reductions, as well as progress towards strictmode compatibility.

pkg: Upgrade to antd 4

---

packages/babel-preset-anansi/README.md
packages/babel-preset-anansi/index.js
packages/webpack-config-anansi/package.json
yarn.lock

Incorporating https://github.com/babel/babel-loader/pull/826/files

feat: Automatically detect webpack target in babel

---

examples/typescript/package.json
packages/webpack-config-anansi/.babelrc
packages/webpack-config-anansi/package.json
yarn.lock

BREAKING CHANGE: Required node 10

pkg: Bump a few webpack plugins

---

packages/webpack-config-anansi/README.md
packages/webpack-config-anansi/media.d.ts
packages/webpack-config-anansi/src/base/index.js

- Added support for .avif image files
- updated readme

Added .avif support

---

packages/webpack-config-anansi/package.json
packages/webpack-config-anansi/src/base/scss.js
yarn.lock

Latest postcss, which means changing config. Also finalizes webpack 5 support.
More info:
https://github.com/postcss/autoprefixer/releases/tag/10.0.0
https://github.com/postcss/postcss/releases/tag/8.0.0
https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0

pkg: Major: autoprefixer, postcss-loader

---

examples/typescript/package.json
examples/typescript/src/github/BaseResource.ts
examples/typescript/src/github/IssueResource.tsx
examples/typescript/src/navigation/Nav.tsx
examples/typescript/src/pages/Issues/index.tsx
examples/typescript/src/pages/PostDetail/post.stories.tsx
packages/eslint-plugin/package.json
packages/generator-js/package-lock.json
packages/generator-js/src/anansi-splash/templates/src/resources/ExchangeRatesResource.ts
packages/generator-js/src/anansi-splash/templates/stories/price.stories.tsx
packages/generator-js/src/spa/index.ts
packages/generator-js/src/spa/templates/src/RootProvider.tsx
packages/generator-js/src/storybook/index.ts
packages/generator-js/src/storybook/templates/.storybook/preview.tsx
yarn.lock

- Example: Update to full release of Rest Hooks
- generator: Update to full release; update sample code based on latest recommendations in v5 docs

enhance: Update codgen with latest Rest Hooks 5 practices

---

.github/dependabot.yml

internal: Setup dependabot

---

.github/workflows/lighthouse.yml
examples/linaria/webpack.config.js
examples/typescript/lighthouserc.js

```
- name: Run Lighthouse
uses: foo-software/lighthouse-check-action@master
with:
accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
author: ${{ github.actor }}
branch: ${{ github.ref }}
outputDirectory: /tmp/artifacts
configFile: ./examples/typescript/lighthouserc.js
sha: ${{ github.sha }}
urls: 'https://ntucker.true.io'
- name: Upload artifacts
uses: actions/upload-artifact@master
with:
name: Lighthouse reports
path: /tmp/artifacts
```

feat: Add lighthouse checks

---

.commitlintrc.js

Shamelessly stolen from https://github.com/streetmix/streetmix/pull/2213
Underlying issue: https://github.com/streetmix/streetmix/pull/2213

internal: Don't break lingint on dependabot

---

.github/workflows/bundle_size.yml

Give general idea of systemic changes to production builds based on tooling

internal: Add compressed size tracking for example project

---

packages/webpack-config-anansi/README.md
packages/webpack-config-anansi/package.json
packages/webpack-config-anansi/src/base/index.js
packages/webpack-config-anansi/src/dev.js
packages/webpack-config-anansi/src/index.js
packages/webpack-config-anansi/src/prod.js

Removing complexity as v4 support is already dropped.

enhance: Remove webpack 4 conditionals

---

packages/webpack-config-anansi/src/base/index.js

https://webpack.js.org/guides/asset-modules/

enhance: Use webpack 5 asset modules

---

packages/generator-js/src/storybook/index.ts
packages/generator-js/src/webpack/index.ts

This should help performance, as well as race conditions with install order.

internal: Install packages with extendJSON first

---

packages/webpack-config-anansi/README.md
packages/webpack-config-anansi/src/base/css.js
packages/webpack-config-anansi/src/dev.js
packages/webpack-config-anansi/src/index.js
packages/webpack-config-anansi/src/nobuild.js
packages/webpack-config-anansi/src/prod.js
yarn.lock

Allows opting out of special global styles, as well as configuring another directory for use. For back-compat reasons, it defaults to 'style'

feat: Add globalStyleDir option

---

packages/cli/run.js

Fixes #300
In case a user doesn't have the default `code` or a specified IDE with $VISUAL - tell them how they might get autolaunching to work in the future.

enhance: Gracefully handle no IDE

---

packages/generator-js/package.json
packages/generator-js/src/app/ConfigureGenerator.ts
packages/generator-js/src/app/index.ts
packages/generator-js/src/base/index.ts
packages/generator-js/src/circle/index.ts
packages/generator-js/src/github-actions/index.ts
packages/generator-js/src/library/index.ts
packages/generator-js/src/license/index.ts
packages/generator-js/src/rollup/index.ts
packages/generator-js/src/spa/index.ts
packages/generator-js/src/storybook/index.ts
packages/generator-js/src/testing/index.ts
packages/generator-js/src/utils.ts
packages/generator-js/src/webpack/index.ts
packages/generator-js/tsconfig.json
yarn.lock

New version of yeoman. Has improved package.json handling - dynamic detection of package tool.

yeoman-generator

---

salus.yaml
yarn.lock

Updated yarn.lock as much as possible and filed bugs on downstream packages.

internal: Don't break on un-fixable downstream deps

---

package.json
yarn.lock

Package: normalize-url
Patched in: >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1
Dependency of: @anansi/cli
More info: https://www.npmjs.com/advisories/1755
Severity: high
Title: Regular Expression Denial of Service
ID: 1755
Package: normalize-url
Patched in: >=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1
Dependency of: @anansi/webpack-config
More info: https://www.npmjs.com/advisories/1755
Severity: high
Title: Regular Expression Denial of Service
ID: 1755

internal: normalize-url security pkg

---

examples/linaria/package.json
examples/linaria/tsconfig.json
examples/typescript/package.json
examples/typescript/tsconfig.json
package.json
packages/babel-preset-anansi/package.json
packages/cli/package-lock.json
packages/generator-js/src/library/index.ts
packages/generator-js/src/spa/index.ts
packages/generator-js/src/spa/templates/src/index.tsx
packages/generator-js/src/spa/templates/tsconfig.json
packages/webpack-config-anansi/package.json
yarn.lock

- Use in example projects
- Support peerDep ranges
- Update project initialization to use 18 line instead of 'experimental'
https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html
https://github.com/reactwg/react-18/discussions/37

feat: Support react 18

---

examples/linaria/src/App.tsx
examples/linaria/src/index.tsx
examples/typescript/src/components/ErrorBoundary/index.tsx
examples/typescript/src/pages/Issues/index.tsx
examples/typescript/src/pages/Posts/PostForm.tsx
packages/eslint-plugin/package.json
packages/webpack-config-anansi/src/prod.js
yarn.lock

BREAKING CHANGE: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0

pkg: @typescript-eslint/eslint-plugin, @typescript-eslint/parser major

---

.github/workflows/commitlint.yml

internal: Upgrade commitlint to v4

---

examples/linaria/package.json
package.json
packages/generator-js/src/webpack/index.ts
packages/webpack-config-anansi/package.json
packages/webpack-config-anansi/src/base/css.js
packages/webpack-config-anansi/src/base/index.js
packages/webpack-config-anansi/src/base/linariaFileCache.js
yarn.lock

[fix for the issue](https://github.com/callstack/linaria/pull/883)

pkg: linaria from 3-beta.13 to 3-beta.17

---

packages/webpack-config-anansi/package.json
packages/webpack-config-anansi/src/plugins/refreshOverlayModule.js
yarn.lock

Workaround https://github.com/callstack/linaria/issues/897 by conditionally importing only when window is available.

pkg: @linaria/webpack5-loader to beta.17

---

.circleci/config.yml

https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

internal: Update circleci image

---

examples/typescript/.storybook/main.js
examples/typescript/package.json
examples/typescript/src/pages/Posts/index.tsx
examples/typescript/src/pages/Posts/post.stories.tsx
examples/typescript/stories/index.stories.tsx
package.json
packages/webpack-config-anansi/package.json
yarn.lock

Finally the only package resolution we need is for security.
Command from https://chromatic-ui.notion.site/Storybook-7-migration-guide-dbf41fa347304eb2a5e9c69b34503937 was sufficient
No webpack adapter changes needed
Future work: https://storybook.js.org/docs/7.0/react/contribute/framework

pkg: Storybook 7
